# Site settings
title: "Wesley Wong's Resume"
description: "A coding portfolio for Wesley Wong."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Wesley Wong"
resume_title:                   "Software Developer"
resume_contact_email:           "wes.wong@outlook.com"
resume_contact_telephone:       "778-999-4274"
resume_contact_address:         "550 Pacific St., Vancouver"
resume_header_contact_info: "550 Pacific St., Vancouver | 778-999-4274 | wes.wong@outlook.com"
resume_header_intro: "<p>While trying to escape a stock boy job at Kin's market I learned to code a python asteroids game. It was very simple: you control a ship and can fire missiles, but don't touch the asteroids, or you will explode, showing a Game Over. At least it should, except the ship kept on exploding, infinitely. I spent hours on this silly little project, and in doing so realized how much fun it is to code.</p><p >I went to the Lighthouse Labs, where I met like-minded people and learned the basics, then, from my cohort of ~20 job-seekers, was offered an opportunity to return as an intern. This helped me sharpen my basics. At Machool, I switched from Ruby/React to NodeJS+Express/Angular. Here we used the agile development, and where I began to specialize in building efficient, intuitive (and beautiful) applications.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/wesley-wong"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/wesley-wong-3202a0138/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
